Notes on setting up the environment for an app.

== Getting a machine
First thing is to obtain a machine you will use for development and hosting the app. Simplest is to get virtual machine from a place like digital ocean or linode. This will get you a machine with linux and the ability to serve content as a server.

== Connect to the machine
Now that you have a machine you will need to connect to it. If you are on windows you will need to download and set up Putty and Cygwin/X Server.

=== Setting up Putty and X Server
Putty allows you to SSH into a machine. X Server allows you to use "X11 forwarding" which in essence allows you to run a code editor on your remote machine and see it on your screen. You need to enable that in putty in Connection->SSh->X11->Enable X11 forwarding.

== Create yourself (and others) an account
Working in the root account is dangerous so create yourself and others you will be working with accounts. Give yourself root privs.

== First server! Test connection
Now that you can connect through Putty we can actually already create a webserver that serves files. All it takes is one line! First create a folder which you will display to the whole wide world:

`mkdir awesomeness`  

`cd awesomeness`  

`echo "<h1>Hello World!</h1>" > hello.html`  

And now run the server:

`python -m SimpleHTTPServer 9000`

Now you should be able to connect to your machine and see the file you created by hitting the url of the form `xxx.xxx.xxx.xxx:9000` where `xxx.xxx.xxx.xxx` is the IP of your machine.

Upon going to that url you should see in your Putty console that someone made a connection.

Ctrl-c to stop the server.

== Obtain a domain name
Typing in a URL everytime is unpleasant and not user friendly. For $10-$50 you can get your own domain name. Go to namecheap.com or other domain name provider and buy yourself a domain.

== Set up domain
Once you have a domain, you will want to point it to your server. This is done through what is called an A-record. Read up more on A-records and the other types of records here - https://en.wikipedia.org/wiki/List_of_DNS_record_types.

Set your domain to point to the IP address of your server.

=== Test again
You can run a server and test your domain name setup as before by running:

`python -m SimpleHTTPServer 9000`

and this time connecting to <yourdomain>:9000.

You can omit the 9000 and hit the default port 80 by running this instead:

`sudo python -m SimpleHTTPServer`

